// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAzAQOddtiK3e7bqoU7ug_Lzx7iYc6aPM',
    appId: '1:605200515740:web:da6a681fd2c981f5786359',
    messagingSenderId: '605200515740',
    projectId: 'clothingstore-64882',
    authDomain: 'clothingstore-64882.firebaseapp.com',
    storageBucket: 'clothingstore-64882.appspot.com',
    measurementId: 'G-J92E96M2ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwdfB6pP5Pkdd9YKBQ6IpF49VBhv-295A',
    appId: '1:605200515740:android:f6675e7c4ffea5f1786359',
    messagingSenderId: '605200515740',
    projectId: 'clothingstore-64882',
    storageBucket: 'clothingstore-64882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlJc7mihN4nO1o_dprdr0J95a2VTOzvY',
    appId: '1:605200515740:ios:0d150b43bd3c568f786359',
    messagingSenderId: '605200515740',
    projectId: 'clothingstore-64882',
    storageBucket: 'clothingstore-64882.appspot.com',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGlJc7mihN4nO1o_dprdr0J95a2VTOzvY',
    appId: '1:605200515740:ios:4a8316ff8ecb1a2d786359',
    messagingSenderId: '605200515740',
    projectId: 'clothingstore-64882',
    storageBucket: 'clothingstore-64882.appspot.com',
    iosBundleId: 'com.example.shoppingapp.RunnerTests',
  );
}
